// Front view (facing the player). Drawn as a left half and mirrored, so it is symmetric.
import { spidermanSideArt } from './spidermanSideArt';
import { Sprite } from './types';

export const spidermanFront: Sprite = {
  colors: spidermanSideArt.colors,
  rows: [
    '........aaaaaaa........',
    '......aacccccccaa......',
    '.....acccdddddccca.....',
    '....acccdddddddccca....',
    '....abccddcdcddccba....',
    '....abaacccccccaaba....',
    '....aakkacccccakkaa....',
    '....aakkkkacakkkkaa....',
    '....abaakkacakkaaba....',
    '....abccaaacaaaccba....',
    '....abcccccccccccba....',
    '....abbcccccccccbba....',
    '.....abbcccccccbba.....',
    '......abbcccccbba......',
    '.......aabbbbbaa.......',
    '........abbcbba........',
    '....aaaabcccccbaaaa....',
    '...abccbbcccccbbccba...',
    '..abcddcbcccccbcddcba..',
    '..ahccddcbcccbcddccha..',
    '.ahcacdccacccaccdcacha.',
    '.ahcacccccaaacccccacha.',
    '.ahcacbccaaaaaccbcacha.',
    '.ahcacccccaaacccccacha.',
    '.ahcacbccacacaccbcacha.',
    '.ahcabcccccccccccbacha.',
    '.ahcabbcccccccccbbacha.',
    '.ahcaabbcccccccbbaacha.',
    '.acdaaajhhhhhhhjaaadca.',
    '.acdcaahhhiiihhhaacdca.',
    '..aaa.ahhhhhhhhha.aaa..',
    '......ahhhhahhhha......',
    '......ahhha.ahhha......',
    '......ajhha.ahhja......',
    '......ajhha.ahhja......',
    '......abcca.accba......',
    '......abcda.adcba......',
    '......abcda.adcba......',
    '......abcca.accba......',
    '......abcca.accba......',
    '......abcca.accba......',
    '.....abccca.acccba.....',
    '.....abcdca.acdcba.....',
    '.....abccca.acccba.....',
    '.....aaaaaa.aaaaaa.....'
  ]
};
