"""Convert upscaled pixel art into a voxel sprite module for the game.

Usage:
  python3 scripts/sprite_to_grid.py src/assets/sprites/spiderman-normal.png spidermanSideArt \
    > src/components/sprites/spidermanSideArt.ts
  python3 scripts/sprite_to_grid.py path/to/art.png myArt 1 > src/components/sprites/myArt.ts

Only art in the game's own style belongs in the game; reference pictures live in references/.

The optional third argument is the art's pixel size in image pixels (auto-detected if omitted).

Detects the art's pixel size, samples one color per art pixel, crops the empty
border, and prints a TypeScript Sprite (see src/components/sprites/types.ts).
White (or transparent) pixels are treated as empty.
"""

import string
import sys
from collections import Counter

from PIL import Image


def block_size(im):
    """Most common run length of identical pixels along the rows."""
    runs = Counter()
    w, h = im.size
    for y in range(0, h, 3):
        prev, n = None, 0
        for x in range(w):
            p = im.getpixel((x, y))
            if p == prev:
                n += 1
            else:
                if prev is not None:
                    runs[n] += 1
                prev, n = p, 1
    return min(n for n, _ in runs.most_common(3))


def is_empty(rgba):
    r, g, b, a = rgba
    return a < 128 or (r, g, b) == (255, 255, 255)


# Enclosed white areas up to this many art pixels are drawn (eye lenses, highlights);
# bigger ones are gaps in the pose (e.g. between an arm and the body) and stay empty.
MAX_ENCLOSED_WHITE = 8


def fill_enclosed_white(im, size, rows, palette, keys):
    h, w = len(rows), len(rows[0])
    seen = set()
    fills = {}
    for r0 in range(h):
        for c0 in range(w):
            if rows[r0][c0] != "." or (r0, c0) in seen:
                continue
            region, touches_edge, stack = [], False, [(r0, c0)]
            while stack:
                r, c = stack.pop()
                if (r, c) in seen or not (0 <= r < h and 0 <= c < w) or rows[r][c] != ".":
                    continue
                seen.add((r, c))
                region.append((r, c))
                touches_edge |= r in (0, h - 1) or c in (0, w - 1)
                stack += [(r + 1, c), (r - 1, c), (r, c + 1), (r, c - 1)]
            if not touches_edge and len(region) <= MAX_ENCLOSED_WHITE:
                for cell in region:
                    fills[cell] = True
    filled = []
    for r, row in enumerate(rows):
        out = ""
        for c, ch in enumerate(row):
            px = im.getpixel((c * size + size // 2, r * size + size // 2))
            if (r, c) in fills and px[3] >= 128:
                hexcolor = "#%02x%02x%02x" % px[:3]
                if hexcolor not in palette:
                    palette[hexcolor] = next(keys)
                ch = palette[hexcolor]
            out += ch
        filled.append(out)
    return filled


def main(path, name, size=None):
    im = Image.open(path).convert("RGBA")
    size = int(size) if size else block_size(im)
    w, h = im.size
    keys = iter(string.ascii_letters)
    palette = {}
    rows = []
    for by in range(0, h - size + 1, size):
        row = ""
        for bx in range(0, w - size + 1, size):
            px = im.getpixel((bx + size // 2, by + size // 2))
            if is_empty(px):
                row += "."
                continue
            hexcolor = "#%02x%02x%02x" % px[:3]
            if hexcolor not in palette:
                palette[hexcolor] = next(keys)
            row += palette[hexcolor]
        rows.append(row)

    # White is only background where it connects to the edge of the image;
    # enclosed white (like eye lenses) is part of the drawing.
    rows = fill_enclosed_white(im, size, rows, palette, keys)

    # Crop empty border
    while rows and set(rows[0]) == {"."}:
        rows.pop(0)
    while rows and set(rows[-1]) == {"."}:
        rows.pop()
    left = min(len(r) - len(r.lstrip(".")) for r in rows)
    right = max(len(r.rstrip(".")) for r in rows)
    rows = [r[left:right] for r in rows]

    print(f"// Generated by scripts/sprite_to_grid.py from {path}. Do not edit by hand.")
    print("import { Sprite } from './types';\n")
    print(f"export const {name}: Sprite = {{")
    print("  colors: {")
    for hexcolor, key in sorted(palette.items(), key=lambda kv: kv[1]):
        print(f"    {key}: '{hexcolor}',")
    print("  },")
    print("  rows: [")
    for r in rows:
        print(f"    '{r}',")
    print("  ]")
    print("};")


if __name__ == "__main__":
    main(*sys.argv[1:4])
